var config={

};
//一些配置参数
config.info={
	"website":"www.shuangteng.net",
	"mailfrom":"2894383420@qq.com",
	"mailto":"ftyszyx@sina.com",
	"mailfrompassword":"zaq1XSW2",
	"companyName":"广州双腾科技有限公司"
}
//首页上显示的文章
config.content=[
	{
		"titlepic":"/images/title1.jpg",
		"link":"/showcase?typeid=1001&postname=post3.mk",
		"title":"成功案例",
		"summary":"成功案例的描述文字。"
	},
	{
		"titlepic":"/images/title2.png",
		"link":"/showcase?typeid=1001&postname=post3.mk",
		"title":"成功案例",
		"summary":"成功案例的描述文字。"
	},
	{
		"titlepic":"/images/title3.png",
		"link":"/showcase?typeid=1001&postname=post3.mk",
		"title":"成功案例",
		"summary":"成功案例的描述文字。"
	},
	{
		"titlepic":"/images/title1.jpg",
		"link":"/showcase?typeid=1001&postname=post3.mk",
		"title":"成功案例",
		"summary":"成功案例的描述文字。"
	},
	{
		"titlepic":"/images/title2.png",
		"link":"/showcase?typeid=1001&postname=post3.mk",
		"title":"成功案例",
		"summary":"成功案例的描述文字。"
	},
	{
		"titlepic":"/images/title3.png",
		"link":"/showcase?typeid=1001&postname=post3.mk",
		"title":"成功案例",
		"summary":"成功案例的描述文字。"
	},
];


exports.config=config;
