//产品数据配置文件
var products={

};

//案例类型
products.type=[
	{
		"typename": "高性能隔热膜",
		"typeid":"1001"
	},
	{
		"typename":"原装进口隔热膜",
		"typeid":"1002"
	},
    {
		"typename":"磨砂膜",
		"typeid":"1003"
	},
	{
		"typename":"安全防爆防弹膜",
		"typeid":"1004"
	},

];

//产品介绍
products.post=[
	{
		"posttile":"双面银色隔热膜",
		"typeid":"1001",
		"postpic":"/images/shuangyin.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"铂色隔热膜",
		"typeid":"1001",
		"postpic":"/images/bose.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"绿银隔热膜",
		"typeid":"1001",
		"postpic":"/images/lvse.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"蓝银隔热膜",
		"typeid":"1001",
		"postpic":"/images/lanse.jpg",
		"posttext":"post1.mk"
	},
	{
		"posttile":"灰银隔热膜",
		"typeid":"1001",
		"postpic":"/images/huise.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"金银隔热膜",
		"typeid":"1001",
		"postpic":"/images/jinyin.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"茶色隔热膜",
		"typeid":"1001",
		"postpic":"/images/chase.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"美国强生膜",
		"typeid":"1002",
		"postpic":"/images/johson.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"美国3M膜",
		"typeid":"1002",
		"postpic":"/images/3m.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"美国龙膜",
		"typeid":"1002",
		"postpic":"/images/llumar.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"方格磨砂膜",
		"typeid":"1003",
		"postpic":"/images/baifangge.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"条纹磨砂膜",
		"typeid":"1003",
		"postpic":"/images/bozhaitiaowen.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"艺术磨砂膜",
		"typeid":"1003",
		"postpic":"/images/yishumosha.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"办公厕所磨砂膜",
		"typeid":"1003",
		"postpic":"/images/mosha.jpg",
		"posttext":"post3.mk"
	},
	{
		"posttile":"安全防爆膜",
		"typeid":"1004",
		"postpic":"/images/fangbao.jpg",
		"posttext":"post3.mk"
	}
	
];
exports.products=products;
