//新闻相关
var news={
	"bannerpic":"/img/banner.jpg"
};

//案例文章
news.post=[
	{
		"title":"大沙田光明街七巷31号民宅",
		"posttext":"post1.mk"
	},
	{
		"title":"大沙田光明街七巷31号民宅",
		"posttext":"post1.mk"
	},
	{
		"title":"大沙田光明街七巷31号民宅",
		"posttext":"post1.mk"
	},
	{
		"title":"大沙田光明街七巷31号民宅",
		"posttext":"post1.mk"
	},
	{
		"title":"大沙田光明街七巷31号民宅",
		"posttext":"post1.mk"
	},
	{
		"title":"大沙田光明街七巷31号民宅",
		"posttext":"post1.mk"
	},
];
exports.news=news;